Create 2022_Recipe1
chef-cookbooks/community_cookbook_documentation pull request #26
Opened 2022-10-23 18:44 UTC by upxksha

Crispy Chicken Recipe Added

### Description

### Issues Resolved

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

2024-10-23 23:02 UTC, smith requested changes

2024-10-23 23:02 UTC, smith commented on 2022_Recipe1
> +Then put the chicked in the iced water slowly.
```suggestion
Then put the chicken in the iced water slowly.
```

On line 31 it says `Take out some ice cubes and let it melt in a glass.`

This implies that I am to fit a whole chicken into a glass of ice water. I tried this and received a `ChickenNoFitException`.

2024-10-24 00:11 UTC, mattray commented on 2022_Recipe1
> +Afterwards coat the chicked once again from the flour(ingredient list 1).
"chicken"

2024-10-24 01:45 UTC, doubt72 commented on 2022_Recipe1
> +Chilli Powder
Plz use American spelling per style guide.  One "l" in "chili"

2024-10-24 03:49 UTC, moutons commented
It would be helpful to include the amount of each ingredient as well as the expected preparation. "Onion" on its own might have one user providing a whole onion, and another adding an unspecified amount of onion powder, for example. "Black Pepper" could be interpreted in frightening ways, as well.

From the ingredient list this could be a tasty submission, keep up the good work! I look forward to reviewing your next proposed change.

2024-10-24 16:39 UTC, lnxchk commented on 2022_Recipe1
> +Afterwards coat the chicked once again from the flour(ingredient list 1).
The flour mixture is ingredient list 2.

2024-10-24 16:40 UTC, lnxchk commented on 2022_Recipe1
> +Mix the Ingredients List 1 well and let it marinate for about 1-2 hours.
Is this marinating the chicken? Should the chicken be in large pieces, small pieces, bone-in, boneless. Recommendations on white or dark meat?

2026-04-17 14:43 UTC, clintoncwolfe commented
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).

2026-04-17 14:43 UTC, closed without merging